### ISSUE TITLE
"Overread" from ffplay

### ISSUE THREAD

**Issue by hieyou1** [meekworth/pylwdrone#1]
Hi,

I was using your library following your example, and I was getting this error from ffplay:

```
[mjpeg @ 0x7f8edc83de00] overread 80KB vq=  453KB sq=    0B f=0/0   
[mjpeg @ 0x7f8edc83de00] overread 80KB vq=  454KB sq=    0B f=0/0   
[mjpeg @ 0x7f8edc83de00] overread 80KB vq=  445KB sq=    0B f=0/0   
[mjpeg @ 0x7f8edc83de00] overread 80KB vq=  479KB sq=    0B f=0/0   
[mjpeg @ 0x7f8edc83de00] overread 80KB vq=  490KB sq=    0B f=0/0   
[mjpeg @ 0x7f8edc83de00] overread 80KB vq=  491KB sq=    0B f=0/0   
[mjpeg @ 0x7f8edc83de00] overread 80KB vq=  491KB sq=    0B f=0/0
```
repeated a ton. My stream also looked like the first one you described on Medium, looking "glitched out". In the "EACHINE FPV" app in the iOS App Store, my stream looks perfectly fine. 

As well as this, my drone also doesn't "give enough bytes" in some commands [e.g. "pylwdrone res get"].

My drone also doesn't have an SD card, it's an Eachine E65HW 1080P if that makes any difference.

Thanks for your help!

Edit: I'm on ffplay version 4.3.1 if that helps

**Comment by meekworth** [comment]
It looks like the software version in your drone might be slightly different than the one I have. Since you are still getting some image in a stream, it might still be "lewei"-based. Are you able to run "pylwdrone config get" and retrieve a valid response? If so, what's the version listed?

If that does work, could you also try "pylwdrone file get /proc/self/exe"? That will retrieve the server, which I could take a look at to look for differences.

**Comment by hieyou1** [comment]
`pylwdrone config get`

```
Camera flip:    up
WiFi Channel:   1
WiFi Security:  open
```
wifi details hidden for security but they show up
```
SD card ready:  False
SD card size:   0 MiB
SD card free:   0 MiB
Version:        "v8.4"
Current time:   1969-12-31 18:01:21
success
```

`pylwdrone file get /proc/self/exe`

```
remote file not found
download failed: /proc/self/exe
failure
```

**Comment by hieyou1** [comment]
I also tried with -q and --low-def and this helped but did not fix the issue.

**Comment by meekworth** [comment]
I took a look at the "EACHINE FPV" app, and the "encode_index" function that fixes the stream is different. Would you be willing to run a packet capture to collect traffic over TCP port 7060 while streaming for a few seconds? I could use that to test a modified encode_index to fix the stream for your version.

**Comment by lmore377** [comment]
I have the same issue so here's some info. I couldn't get an emulator working so I just did tcpdump on a rooted phone

pylwdrone config get
`Camera flip:    down
WiFi Channel:   3
WiFi Security:  open
WiFi Name:      
WiFi Password:  12345678
SD card ready:  False
SD card size:   0 MiB
SD card free:   0 MiB
Version:        V91
Current time:   2021-03-28 07:57:02
success
`
Remove .txt from the file names
[tcpdump.pcap.txt](https://github.com/meekworth/pylwdrone/files/6217962/tcpdump.pcap.txt)
[proc-self-exe.txt](https://github.com/meekworth/pylwdrone/files/6217964/proc-self-exe.txt)

I got telnet access with FTP so if you need me to do/pull anything else just let me know.

**Comment by meekworth** [comment]
@lmore377, thanks for the pcap. Interestingly enough, when I extracted the video stream without applying the mysterious byte swap, it played perfectly. It looks like your version doesn't intentionally break the stream.

If you want to test a quick change to see if that fixes the video for you, comment out the "fix_byte" section at lines 567-569 in responses.py.

I can't remember if there is additional parsing for the serial commands. I'll take a look again when I get a chance to also look at the exe file you attached to see what differences there are in your version.

**Comment by lmore377** [comment]
@meekworth I commented those lines out and yeah the video played perfectly

**Comment by hieyou1** [comment]
Sorry for my very late response, I just tried commenting out 567-569 of responses.py and am still having problems. Although with these lines commented out it still works, it now does not work without the lines commented out. Still can't get /proc/self/exe. I can get and send over a pcap if it is still required.

**Comment by DroopCat** [comment]
I'm having the same issue where the video is corrupted halfway with and without the byte swapping.
Somehow the byte swapping function is different, but I can't tell by looking at the decompiled encode_index() function.
I'm stumped.

Drone "Eachine E520"
App "EACHINE FPV"

**Comment by grote** [comment]
Thanks a lot for this code. Helps a lot with getting a video feed from the drone!

I have an Eachine EX5 and get a garbled stream as well with pylwdrone. Only a small strip at the top is visible properly. When commenting out "fix_byte" section, I get a better stream where I can see almost the entire top half, but the bottom half is still garbled. I guess a different byte fixing is needed here.

**Comment by grote** [comment]
@meekworth Here's a very short `pcap` of the video stream: [ex5-video.pcap.gz](https://github.com/meekworth/pylwdrone/files/6670310/ex5-video.pcap.gz). My guess is that the fix for the `encode_index()` function of the "EACHINE FPV" app will work here as well. Mind sharing it, so I can try?

Btw. it seems that your `LW Drone Cam` Android app seems to be expecting every video frame to start with that magic lewei header and thus throws `DroneCamException("Invalid packet header")` for my model.

**Comment by meekworth** [comment]
@grote, interestingly in your pcap, the size field in the header is longer than it should be, so the code isn't finding the lewei header where it should be. I'm looking into if your version plays games with the size field too.

@grote, @DroopCat, if the 'pylwdrone config get' works, could you share that so I can get a collection of versions and start keeping track of the differences?

**Comment by grote** [comment]
> interestingly in your pcap, the size field in the header is longer than it should be, so the code isn't finding the lewei header where it should be.

Strange. Maybe related to the fact that this is 4K video drone, so frames are larger? 

> if the 'pylwdrone config get' works, could you share that so I can get a collection of versions and start keeping track of the differences?

Great idea. Maybe also document the formats in a wiki or something?

Unfortunately, the command doesn't work here:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/pylwdrone", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/pylwdrone/__main__.py", line 25, in main
    ret = args.func(drone, args)
  File "/home/user/.local/lib/python3.9/site-packages/pylwdrone/__main__.py", line 87, in _cmd_config_get
    config = drone.get_config()
  File "/home/user/.local/lib/python3.9/site-packages/pylwdrone/lwdrone.py", line 79, in get_config
    return Config.from_bytes(rcmd.body)
  File "/home/user/.local/lib/python3.9/site-packages/pylwdrone/responses.py", line 139, in from_bytes
    conf._time = datetime.datetime.fromtimestamp(time)
OverflowError: timestamp out of range for platform time_t
```

timestamp is `18446744073709523015`

If I remove the conversation for it, I get:

```
Camera flip:    up
WiFi Channel:   36
WiFi Security:  open
WiFi Name:      
WiFi Password:  12345678
SD card ready:  False
SD card size:   0 MiB
SD card free:   0 MiB
Version:        V300
```

Note that this drone doesn't have an SD card.

**Comment by meekworth** [comment]
@grote, @DroopCat, @hieyou1 - I found the new decode function that I think your versions were using. I implemented the decoder and committed the changes to the master branch here. Pull the latest changes and let me know if that fixes the streaming.

For the versions that don't do any modification of the stream, like with @lmore377's sample, the updated code should handle that as well.

**Comment by grote** [comment]
Awesome, thanks a lot! The stream works perfectly now! :D

Now, we just need to get the lwdronecam app working and I can start flying. Should I create a ticket there for this?

**Comment by hieyou1** [comment]
> @grote, @DroopCat, @hieyou1 - I found the new decode function that I think your versions were using. I implemented the decoder and committed the changes to the master branch here. Pull the latest changes and let me know if that fixes the streaming.
> 
> For the versions that don't do any modification of the stream, like with @lmore377's sample, the updated code should handle that as well.

Can confirm that this works with my version. I'm going to close the issue now-- open it back up again if you start having problems!

P.S. If you want to add drone controls to this library, I'd suggest taking a look at [this library](https://www.npmjs.com/package/dronelib)-- it's built in Node.js, but it contains the basic code to control the drone and it would be awesome if this library had support for actual controls :)
