### ISSUE TITLE
take_picture() function broken

### ISSUE THREAD

**Issue by Nilon123456789** [meekworth/pylwdrone#3]
The take_picture() function is returning a corupted file when run

**Comment by hieyou1** [comment]
Can you send that file as well as a pcap, so we can help figure out what’s going on?

**Comment by Nilon123456789** [comment]
The picture is corect in the drone sd card. here is the cap file and the py script

and here is the error : 
```
File "c:\Users\username\Downloads\Drone\test.py", line 8, in <module>
    fp.write(drone.take_picture())
TypeError: a bytes-like object is required, not 'Picture'
```
[file.zip](https://github.com/meekworth/pylwdrone/files/6777452/file.zip)

**Comment by hieyou1** [comment]
Ah. To write a Picture to a file, you need to write its data.

Use this code: ```py
fp.write(drone.take_picture().data);
```

**Comment by hieyou1** [comment]
Oops my bad, remove the parenthesis after `data`:

```py
fp.write(drone.take_picture().data)
```

**Comment by Nilon123456789** [comment]
Worked thanks maybe update the readme with this tweak
