### ISSUE TITLE
Improvment  Stream live video reduce lag with one line command 

### ISSUE THREAD

**Issue by Nilon123456789** [meekworth/pylwdrone#4]
I experience lag when using the stream video command so I tweak it to reduce input lag. Here is the sujested addon to put in to the read me juste after the stream live video header

#### If input is lagy use this
```
$ pylwdrone stream start --out-file - | ffplay -i -fflags nobuffer -flags low_delay -probesize 32 -sync ext -
```

**Comment by hieyou1** [comment]
I made this into a PR, see PR #5

**Comment by Nilon123456789** [comment]
okay thanks
